### ISSUE TITLE
How to select reads to a fixed level

### ISSUE THREAD

**Issue by HaotengYan** [YongxinLiu/EasyMetagenome#1]
Hi Ph.D. Liu,

I am puzzled with the part that how to select a fixed number of reads across all samples in the metagenomic analysis. Is there any software or script that is fittable to humann2 pipeline?  

Thank you!

**Comment by Y-H-Joe** [comment]
You can use outpost，which is snakemake version，including humann3 pipeline

https://github.com/Y-H-Joe/OUTPOST
