### ISSUE TITLE
Bracken估计丰度，不同样本的结果文件行数不同

### ISSUE THREAD

**Issue by z1242099843** [YongxinLiu/EasyMetagenome#2]
按照 1.Pipeline 里的代码用Bracken重新估算  C1和C2的丰度，但是汇总结果文件时发现，结果文件的行数并不相同。但是Kraken2的结果行数是相同的 ，按照1.Pipeline里的代码可以直接进行合并。下面是bracken的参数-r 100 -l S。
bracken -d ${kraken2_db} -i $work_dir/02_Kraken2/${Sample}.report \
        -r ${len} -l ${tax} -o $work_dir/02_Kraken2/${Sample}.bracken \
        -w $work_dir/02_Kraken2/${Sample}.bracken.report
请问造成这种结果的原因是什么？这样的结果是否有问题？

**Comment by YongxinLiu** [comment]
bracken旧版有问题，请安装2.8及以上新版本。另外代码也在1.2.1中更新，解决了此问题

**Comment by Y-H-Joe** [comment]
可以使用 outpost，是snakemake版本，包含自动丰度估计

https://github.com/Y-H-Joe/OUTPOST
