### ISSUE TITLE
data cannot be download

### ISSUE THREAD

**Issue by chaunceydust** [YongxinLiu/EasyMetagenome#3]
Cannot access http://210.75.224.110/ , so data cannot be download(such as http://210.75.224.110/share/Resfams-proteins.dmnd)

**Comment by YongxinLiu** [comment]
所有软件和数据库可从官网下载，All software and databases can be downloaded from the official website, 备选 optional：
中科院微生物所Institute of Microbiology, Chinese Academy of Sciences：ftp://download.nmdc.cn/tools/ (FileZilla访问) 
百度网盘Baidu Netdisk：https://pan.baidu.com/s/1Ikd_47HHODOqC3Rcx6eJ6Q?pwd=0315

**Comment by Y-H-Joe** [comment]
可以使用 outpost，是snakemake版本，包含数据库自动下载和安装

https://github.com/Y-H-Joe/OUTPOST
