### ISSUE TITLE
Issue regarding output of lefse-plot_features.py from LEfse

### ISSUE THREAD

**Issue by ChrisLee913** [YongxinLiu/EasyMetagenome#5]
Hi, 
I'm new here and found your project interesting and helpful!

But I'm kinda confused about the lefse output for the single feature produced by lefse-plot_features.py. Cuz there is no subclass(SampleID) annotation under the Fig. yield, like your own example result showed:
<img width="940" alt="Screenshot 2023-06-15 at 11 39 23 AM" src="https://github.com/YongxinLiu/EasyMetagenome/assets/95332903/11ba14df-d7ec-4795-a853-f8e845a03055">
only group classification above the bars.

Is it because the input file doesn't include the subclass(SampleID) information?  If so, then how should I insert that info into input file? by format2lefse?  I failed to modify format2lefse Rscript to make it.  Can you help me with this?

**Comment by YongxinLiu** [comment]
The example don't have subclass.

**Comment by Y-H-Joe** [comment]
You can use outpost，which is snakemake version，including LefSE analysis
https://github.com/Y-H-Joe/OUTPOST
